kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.native.disableCompilerDaemon=true

# Force Gradle to use JDK 21 (Azul Zulu 21)
org.gradle.java.home=C:/Users/arsas/.gradle/jdks/azul_systems__inc_-21-amd64-windows.2
